### ISSUE TITLE
Generic settings store object

### ISSUE THREAD

**Issue by brian-at-sri** [SRI-International/gremlin-visualizer#21]
# Current Behavior
We store the vis-network specific settings object in the Redux store.

# Desired behavior
We should store our own abstraction of the settings in the Redux store. Each graph implementation should then keep it's own settings object, and appropriately apply graph specific changes when the Redux store settings updates.

Bonus points if we can also customize the default graph specific settings in constants.js. Or at least make it very easy to change hardcoded defaults. i.e. the graph settings defaults should be specified once, and updates should be selectively made, rather than hardcoding the entire settings value on change.

Do this:
```
const default settings = {
a: 1,
b: 2,
c: 3
}

function onChange(bState) {
  let newSettings = Object.assign({}, {...settings, b: bState})
  graph.setSettings(newSettings)
}
```
Not this:
```
function onChange(bState) {
  graph.setSettings({a: 1, b: bState, c: 3})
}
```

**Comment by brian-blonski** [comment]
Fixed in #24
