### ISSUE TITLE
Saved Queries Panel

### ISSUE THREAD

**Issue by brian-at-sri** [SRI-International/gremlin-visualizer#49]
Add a new tab panel for displaying saved queries. Users should be able to run the query right from the panel.

For now, queries will be saved in a map in src/constants.js. The map should be description to gremlin query code. The saved query should display the query descriptions in a list, with an execute button. Displaying the query code is unnecessary, but it might be nice to have a preview panel.

![Saved Queries](https://github.com/SRI-International/gremlin-visualizer/assets/125314881/522d6bd9-216f-4914-87eb-f9d8715f720a)

**Comment by brian-blonski** [comment]
Depending on space, we may have to move to a vertical icon tab bar along the right edge instead of a horizontal one along the top.
